#! /bin/bash
# Updater RDP
echo "Updating apt-get"
apt-get update
echo "Installing qemu-system-x64"
apt-get install qemu-system-x86 -y
rm -rf 10.ENT.x64.EVAL.US-English 10.ENT.x64.EVAL.US-English.img 10.ENT.x64.EVAL.US-English.gz ngrok ngrok.zip ng.sh > /dev/null 2>&1
echo "Updating/installing Windows, Size Windows: 3.9 GB. Its take a view minutes"
wget -O 10.ENT.x64.EVAL.US-English.gz https://archive.org/download/10.ENT.x64.EVAL.USEnglish_201902/10.ENT.x64.EVAL.US-English.gz
echo "Extracting Files Windows"
gunzip 10.ENT.x64.EVAL.US-English.gz
mv 10.ENT.x64.EVAL.US-English 10.ENT.x64.EVAL.US-English.img
clear
echo "Your RDP Is Up-To-Date"
echo "You can type ./runwin to Run your RDP"
echo "If you don't have script ./runwin, you can install with type "wget -O runwin.sh https://raw.githubusercontent.com/marchello12/fix/main/runwin""
